# path for datasets
datapath: "/mnt/nfs/share/guangjiel/data/cycleGAN"

# params for load data
resize_size: 700
crop_size: 600
channel: 1
train_batch_size: 3
test_batch_size: 10
buffer_size: 100
repeat: null

# params for training
epochs: 100
lr: 0.0001
beta1: 0.9
save_epoch_freq: 50

# params for loss function
loss_mode: "gan"
gradient_penalty_mode: null
gradient_penalty_weight: 10
cycle_weight: 1
idenity_weight: 5

# params for NN
input_nc: 1
output_nc: 1
ngf: 32
ndf: 32
n_blocks: 6
n_downsampling: 3
n_layers: 3
norm: "instance_norm"
padding: "same"

log_path: "result/logs"
is_Distributed: null
